
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace myproj {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;


    public partial class MyView : Terminal.Gui.Views.Window {

        private Terminal.Gui.Views.Label label;

        private Terminal.Gui.Views.Button startButton;

        private void InitializeComponent() {
            this.startButton = new Terminal.Gui.Views.Button();
            this.label = new Terminal.Gui.Views.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Overlapped;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Title = "Press Esc to quit";
            this.label.Width = Dim.Auto();
            this.label.Height = Dim.Auto();
            this.label.X = Pos.Center();
            this.label.Y = Pos.Center();
            this.label.Visible = true;
            this.label.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.label.CanFocus = false;
            this.label.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.label.Data = "label";
            this.label.Text = "Press start";
            this.label.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label);
            this.startButton.Width = Dim.Auto();
            this.startButton.Height = Dim.Auto();
            this.startButton.X = Pos.Center();
            this.startButton.Y = Pos.Center() + 1;
            this.startButton.Visible = true;
            this.startButton.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.startButton.CanFocus = true;
            this.startButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.Opaque;
            this.startButton.Data = "button1";
            this.startButton.Text = "Start";
            this.startButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.startButton.IsDefault = false;
            this.Add(this.startButton);
        }
    }
}
