//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
using Toggl.Api;

namespace myproj;

public partial class MyView
{
    private readonly TogglClient _client = new(new TogglClientOptions
    {
        Key = "77775ba928442e3ea39bcb4258a52710"
    });

    public MyView()
    {
        InitializeComponent();

        startButton.Accepting += async (s, e) =>
        {
            e.Handled = true;
            await GenerateTimesheet();
        };
    }

    private async Task GenerateTimesheet()
    {
        var date = DateTime.Today.AddMonths(-1);
        label.Text = "Fetching time entries from Toggl";

        var timeEntries = await Timesheet.Csharp.GetTimeEntriesAsync(_client, date);
        label.Text = "Generating Excel file";

        Excel.generateExcel(@"c:\temp\TS_VD.xlsx", date, "Vincent", "Delcoigne", timeEntries);
        await Task.Run(() => Excel.generateExcel(@"c:\temp\TS_VD.xlsx", date, "Delcoigne", "Vincent", timeEntries));

        Common.openFile(@"c:\temp\TS_VD.xlsx");
        int i = Terminal.Gui.Views.MessageBox.Query("Outlook", "Send email ?", "Ok", "Cancel");
        Console.WriteLine(i);

        label.Text = "Done";
    }
}
