<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <AssemblyName>Taggl</AssemblyName>
        <ApplicationIcon>etienne.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Types.fs" />
        <Compile Include="Toggl.Api.fs" />
        <Compile Include="Timesheet.fs" />
        <Compile Include="Excel.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FsExcel" Version="0.0.49" />
      <PackageReference Include="FSharp.SystemCommandLine" Version="0.17.0-beta4" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
      <PackageReference Include="Spectre.Console" Version="0.47.0" />
      <PackageReference Include="Toggl.Api" Version="8.0.7" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>


    <ItemGroup>
      <None Include="etienne.ico" />
    </ItemGroup>

</Project>
