//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
using Terminal.Gui;

namespace GuiTerminal;

public partial class MyView
{
    public MyView()
    {
        InitializeComponent();
        // this.progressBar.ProgressBarStyle = ProgressBarStyle.MarqueeContinuous;
        this.progressBar.Fraction = 0.5f;
    }

}
