
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace GuiTerminal {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;


    public partial class MyView : Terminal.Gui.Window {


        private Terminal.Gui.ProgressBar progressBar;

        private void InitializeComponent() {
            this.progressBar = new Terminal.Gui.ProgressBar();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.CanFocus = false;
            this.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.progressBar.Width = 10;
            this.progressBar.Height = 1;
            this.progressBar.X = 0;
            this.progressBar.Y = 0;
            this.progressBar.Visible = true;
            this.progressBar.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.progressBar.CanFocus = false;
            this.progressBar.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.progressBar.Data = "progressBar";
            this.progressBar.Text = "100%";
            this.progressBar.TextAlignment = Terminal.Gui.Alignment.Start;
            this.progressBar.Fraction = 1F;
            this.progressBar.BidirectionalMarquee = true;
            this.progressBar.ProgressBarStyle = Terminal.Gui.ProgressBarStyle.Blocks;
            this.progressBar.ProgressBarFormat = Terminal.Gui.ProgressBarFormat.Simple;
            this.progressBar.SegmentCharacter = new System.Text.Rune('▌');
            this.Add(this.progressBar);
        }
    }
}
