<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="ExampleWindow.fs" />
        <Compile Include="Program.fs"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Terminal.Gui" Version="2.0.0-develop.4519" />
      <PackageReference Include="Terminal.Gui.Elmish" Version="3.0.0-v2-develop.2329-v1" />
    </ItemGroup>

</Project>
